/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.SheltersManagementRoleWorkArea;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.SheltersManagement;
import Business.Shelters.Shelters;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.AdministrativeWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mengtingyang
 */
public class SheltersManagementWorkRequestJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private UserAccount account;
    private SheltersManagement sheltersManagement;
    private Enterprise enterprise;
    private EcoSystem business;
    private AdministrativeWorkRequest request;

    /**
     * Creates new form SheltersManagementWorkRequestJPanel
     */
    SheltersManagementWorkRequestJPanel(JPanel userProcessContainer, UserAccount account, EcoSystem business, Enterprise enterprise, SheltersManagement sheltersManagement,
            AdministrativeWorkRequest request) {
        initComponents();
        this.account = account;
        this.business = business;
        this.enterprise = enterprise;
        this.userProcessContainer = userProcessContainer;
        this.sheltersManagement = sheltersManagement;
        this.request = request;

        populateSheltersTable();
        lableNeedNumber.setText(request.getMessage());
    }

    public void populateSheltersTable() {
        DefaultTableModel model = (DefaultTableModel) tblShelters.getModel();

        model.setRowCount(0);
        for (Shelters shelters : business.getSheltersDirectory().getSheltersList()) {
            Object[] row = new Object[4];
            row[0] = shelters;
            row[1] = shelters.getSheleterStatus();
            row[2] = shelters.getSheleterSpaceNumber();
            row[3] = shelters.getSheltersType().getValue();
            model.addRow(row);
        }
    }

    ArrayList<Integer> sumChooseNumberList = new ArrayList<Integer>();
    //int sumChooseNumber = 0;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShelters = new javax.swing.JTable();
        btnChoose = new javax.swing.JButton();
        spinNumber = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRequest = new javax.swing.JTable();
        lableNumber = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnSend = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lableNeedNumber = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnSendHos = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 227, 227));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ooopic_1510889295.png"))); // NOI18N
        jLabel1.setText("Shelters     List");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ooopic_1510889304.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tblShelters.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Status", "Space Number", "Shelter Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblShelters);

        btnChoose.setBackground(new java.awt.Color(255, 255, 255));
        btnChoose.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnChoose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ooopic_1510889288.png"))); // NOI18N
        btnChoose.setText("Choose this shelter");
        btnChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseActionPerformed(evt);
            }
        });

        spinNumber.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        spinNumber.setToolTipText("Please enter the integer ");

        tblRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Number", "Shelter Type", "Shelter Status"
            }
        ));
        jScrollPane1.setViewportView(tblRequest);

        lableNumber.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lableNumber.setForeground(new java.awt.Color(0, 153, 255));
        lableNumber.setText("Number");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 153, 255));
        jLabel8.setText("Remain Number of People:");

        btnSend.setBackground(new java.awt.Color(255, 255, 255));
        btnSend.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ooopic_1510889282.png"))); // NOI18N
        btnSend.setText("Send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 153, 255));
        jLabel9.setText("Need Number of People:");

        lableNeedNumber.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        lableNeedNumber.setForeground(new java.awt.Color(0, 153, 255));
        lableNeedNumber.setText("Number");

        btnSendHos.setBackground(new java.awt.Color(255, 255, 255));
        btnSendHos.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        btnSendHos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/ooopic_1510889267.png"))); // NOI18N
        btnSendHos.setText("Send to Hospital");
        btnSendHos.setEnabled(false);
        btnSendHos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendHosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(btnChoose)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(spinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 37, Short.MAX_VALUE)))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lableNeedNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lableNumber))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSend, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSendHos))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(spinNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChoose, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNeedNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lableNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSend)
                    .addComponent(btnSendHos))
                .addContainerGap(32, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SheltersManagementRoleWorkAreaJPanel sysAdminwjp = (SheltersManagementRoleWorkAreaJPanel) component;
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblShelters.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(null, "Please select a row from table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int chooseNumber = (int) spinNumber.getValue();

        if (chooseNumber > Integer.parseInt(request.getMessage())) {
            JOptionPane.showMessageDialog(null, "The number exceeds need!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        sumChooseNumberList.add(chooseNumber);
        int sumChooseNumber = 0;
        for (int i = 0; i < sumChooseNumberList.size(); i++) {
            sumChooseNumber = sumChooseNumber + sumChooseNumberList.get(i);

        }
        int remainNumber = Integer.parseInt(request.getMessage()) - sumChooseNumber;

        if (remainNumber < 0) {
            JOptionPane.showMessageDialog(null, "The sum of number exceeds need", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        if (remainNumber == 0) {
            JOptionPane.showMessageDialog(null, "The number is enough. Please submit", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        lableNumber.setText(String.valueOf(remainNumber));

        Shelters shelters = (Shelters) tblShelters.getValueAt(selectedRow, 0);
        if(shelters.getSheleterSpaceNumber()<5){
         JOptionPane.showMessageDialog(null, "Careful! The number is nearly not enough!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
         if(shelters.getSheleterSpaceNumber()==0){
         JOptionPane.showMessageDialog(null, "The number is not enough! Please choose other one!", "Warning", JOptionPane.WARNING_MESSAGE);
          return;
        }
           if(shelters.getSheleterSpaceNumber()<chooseNumber){
         JOptionPane.showMessageDialog(null, "The number of this Shelter is not enough!", "Warning", JOptionPane.WARNING_MESSAGE);
          return;
        }
        
        Shelters sheltersChoose = request.addShelters(shelters.getSheltersName(), chooseNumber, shelters.getSheleterStatus(), shelters.getSheltersType());
        DefaultTableModel model = (DefaultTableModel) tblRequest.getModel();
        model.setRowCount(0);

        for (Shelters shelter : request.getRequest_Shelters()) {
            Object[] row = new Object[4];
            row[0] = shelter;
            row[1] = shelter.getSheleterSpaceNumber();
            row[2] = shelter.getSheltersType();
            row[3] = shelter.getSheleterStatus();
            model.addRow(row);
        }

        int newInventory = shelters.getSheleterSpaceNumber() - chooseNumber;
        shelters.setSheleterSpaceNumber(newInventory);

        populateSheltersTable();

    }//GEN-LAST:event_btnChooseActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (Integer.parseInt(lableNumber.getText()) != 0) {
            JOptionPane.showMessageDialog(null, "Not Enough! ", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (tblRequest.getRowCount() < 0) {
            JOptionPane.showMessageDialog(null, "No Content! ", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {
            request.setStatus("Completed");
            request = new AdministrativeWorkRequest();
            JOptionPane.showMessageDialog(null, "Submit Successful! ", "Warning", JOptionPane.WARNING_MESSAGE);
            btnSend.setEnabled(false);
            btnSendHos.setEnabled(true);
            
        }
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendHosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendHosActionPerformed
        // TODO add your handling code here:
        SheltersHospital manageNetworkJPanel = new SheltersHospital(userProcessContainer, account, business, enterprise,
        sheltersManagement, (AdministrativeWorkRequest) request);
        userProcessContainer.add("SheltersHospital", manageNetworkJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnSendHosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnChoose;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnSendHos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lableNeedNumber;
    private javax.swing.JLabel lableNumber;
    private javax.swing.JSpinner spinNumber;
    private javax.swing.JTable tblRequest;
    private javax.swing.JTable tblShelters;
    // End of variables declaration//GEN-END:variables
}
