/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.admin;

import Business.Business;
import UserInterface.LoginJPanel;
import UserInterface.MonitorSalesPerformance.ManageSearchJPanel;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author butte
 */
public class SystemAdminWorkArea extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private Business business;

    /**
     * Creates new form SystemAdminWorkArea
     */
   

    public SystemAdminWorkArea(JPanel userProcessContainer, Business business) {
       initComponents();
       this.userProcessContainer=userProcessContainer;
       this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnMngUserAccount = new javax.swing.JButton();
        btnMonitorPerformance = new javax.swing.JButton();

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("System Admin Work Area");

        btnMngUserAccount.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMngUserAccount.setText("Manage User Accounts >>");
        btnMngUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMngUserAccountActionPerformed(evt);
            }
        });

        btnMonitorPerformance.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMonitorPerformance.setText("Monitor Sales Performance >>");
        btnMonitorPerformance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMonitorPerformanceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(262, 262, 262)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMonitorPerformance)
                            .addComponent(btnMngUserAccount))))
                .addContainerGap(281, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(92, 92, 92)
                .addComponent(btnMngUserAccount)
                .addGap(31, 31, 31)
                .addComponent(btnMonitorPerformance)
                .addContainerGap(279, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMngUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMngUserAccountActionPerformed
        // TODO add your handling code here:
        MngUserAccountJPanel panel= new  MngUserAccountJPanel(userProcessContainer,business);
        userProcessContainer.add("MngUserAccountJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnMngUserAccountActionPerformed

    private void btnMonitorPerformanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMonitorPerformanceActionPerformed
        // TODO add your handling code here:
        ManageSearchJPanel panel= new  ManageSearchJPanel(userProcessContainer,business);
        userProcessContainer.add("ManageSearchJPanel",panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_btnMonitorPerformanceActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMngUserAccount;
    private javax.swing.JButton btnMonitorPerformance;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
