/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import User.FinancialAccounts;
/**
 *
 * @author mengtingyang
 */
public class financialAccountsViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form financialAccountViewPanel
     */
    public financialAccountsViewPanel(FinancialAccounts financialaccounts) {
        initComponents();
        displayAccounts(financialaccounts);
    }

     private void displayAccounts (FinancialAccounts financialaccounts)
    {
      String accountsCheckingAccountActiveStatus=financialaccounts.getCheckingAccountActiveStatus();
      checkingAccountActiveStatusTextField.setText(accountsCheckingAccountActiveStatus);
      
      String accountsCheckingAccountCreationDate=financialaccounts.getCheckingAccountCreationDate();
      checkingAccountCreationDateTextField.setText(accountsCheckingAccountCreationDate);
      
      String accountsCheckingAccountCredit=financialaccounts.getCheckingAccountCredit();
      checkingAccountCreditTextField.setText(accountsCheckingAccountCredit);
      
      String accountsCheckingAccountDebt=financialaccounts.getCheckingAccountDebt();
      checkingAccountDebtTextField.setText(accountsCheckingAccountDebt);
      
      String accountsCheckingAccountNumber=financialaccounts.getCheckingAccountNumber();
      checkingAccountNumberTextField.setText(accountsCheckingAccountNumber);
      
      
      
      
      String accountsSavingAccountActiveStatus=financialaccounts.getSavingAccountActiveStatus();
      savingAccountActiveStatusTextField.setText(accountsSavingAccountActiveStatus);
      
      String accountsSavingAccountCreationDate=financialaccounts.getSavingAccountCreationDate();
      savingAccountCreationDateTextField.setText(accountsSavingAccountCreationDate);
      
      String accountsSavingAccountCredit=financialaccounts.getSavingAccountCredit();
      savingAccountCreditTextField.setText(accountsSavingAccountCredit);
      
      String accountsSavingAccountDebt=financialaccounts.getSavingAccountDebt();
      savingAccountDebtTextField.setText(accountsSavingAccountDebt);
      
      String accountsSavingAccountNumber=financialaccounts.getSavingAccountNumber();
      savingAccountNumberTextField.setText(accountsSavingAccountNumber);
      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        checkingAccountNumberTextField = new javax.swing.JTextField();
        checkingAccountCreationDateTextField = new javax.swing.JTextField();
        checkingAccountActiveStatusTextField = new javax.swing.JTextField();
        checkingAccountDebtTextField = new javax.swing.JTextField();
        checkingAccountCreditTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        savingAccountNumberTextField = new javax.swing.JTextField();
        savingAccountCreationDateTextField = new javax.swing.JTextField();
        savingAccountActiveStatusTextField = new javax.swing.JTextField();
        savingAccountDebtTextField = new javax.swing.JTextField();
        savingAccountCreditTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Malayalam MN", 0, 24)); // NOI18N
        jLabel1.setText("View Your Financial Accounts");

        jLabel2.setText("Checking-Account Number:");

        jLabel3.setText("Checking-Account Creation Date (YYYY/MM/DD):");

        jLabel4.setText("Checking-Account Active Status(Active or Not Active):");

        jLabel5.setText("Checking-Account Debt:");

        jLabel6.setText("Checking-Account Credit:");

        checkingAccountDebtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkingAccountDebtTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Saving-Account Number:");

        jLabel8.setText("Saving-Account Creation Date (YYYY/MM/DD):");

        jLabel9.setText("Saving-Account Active Status(Active or Not Active):");

        jLabel10.setText("Saving-Account Debt:");

        jLabel11.setText("Saving-Account Credit:");

        savingAccountDebtTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingAccountDebtTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(savingAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingAccountCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingAccountActiveStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingAccountDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(savingAccountCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(checkingAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkingAccountCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkingAccountActiveStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkingAccountDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(checkingAccountCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(203, 203, 203))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(checkingAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingAccountCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingAccountActiveStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingAccountDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkingAccountCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(savingAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingAccountCreationDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingAccountActiveStatusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingAccountDebtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(savingAccountCreditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(29, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void checkingAccountDebtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkingAccountDebtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkingAccountDebtTextFieldActionPerformed

    private void savingAccountDebtTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingAccountDebtTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingAccountDebtTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checkingAccountActiveStatusTextField;
    private javax.swing.JTextField checkingAccountCreationDateTextField;
    private javax.swing.JTextField checkingAccountCreditTextField;
    private javax.swing.JTextField checkingAccountDebtTextField;
    private javax.swing.JTextField checkingAccountNumberTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField savingAccountActiveStatusTextField;
    private javax.swing.JTextField savingAccountCreationDateTextField;
    private javax.swing.JTextField savingAccountCreditTextField;
    private javax.swing.JTextField savingAccountDebtTextField;
    private javax.swing.JTextField savingAccountNumberTextField;
    // End of variables declaration//GEN-END:variables
}
